# Generated by Django 2.1 on 2018-12-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='webapp.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('rating', models.CharField(choices=[('terribly', 'Ужасно'), ('poorly', 'Плохо'), ('norm', 'Нормально'), ('good', 'Хорошо'), ('fine', 'Отлично')], default='norm', max_length=20, verbose_name='оценка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating', to='webapp.Article')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('commented_articles', models.ManyToManyField(related_name='comments_articles', through='webapp.Comment', to='webapp.Article', verbose_name='Комментированные статьи')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favored_by', to='webapp.Article', verbose_name='Избранное')),
                ('rated_articles', models.ManyToManyField(related_name='rated_articles', through='webapp.Rating', to='webapp.Article', verbose_name='Оцененные статьи')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='webapp.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='commented_by',
            field=models.ManyToManyField(related_name='commented_by', through='webapp.Comment', to='webapp.User', verbose_name='Комментарий пользователя'),
        ),
        migrations.AddField(
            model_name='article',
            name='rated_by',
            field=models.ManyToManyField(related_name='rated_by', through='webapp.Rating', to='webapp.User', verbose_name='Оценки пользователя'),
        ),
    ]
