# Generated by Django 2.1 on 2018-12-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181216_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='webapp.Comment'),
        ),
    ]
